export default {
    "verificationCodeTitle": "Verification Code - (App Name)",
    "verificationCodeBody": "Here is your confirm code:",
    "welcomeCode": "Welcome to the (App Name),",
    "00005": "Please provide all information to send a code.",
    "00006": "Access denied. No token provided.",
    "00007": "Invalid user id.",
    "00008": "An internal server error occurred, please try again.",
    "00009": "Could not find verified user with the given token and id. Be sure that the account was verified and activated.",
    "00011": "Your session is expired, please log in again.",
    "00012": "Invalid token. the token may have expired.",
    "00013": "Access denied. Please logout from loggedIn device.",
    "00017": "Access denied. You do not have permission to access.",
    "00019": "Access denied. You do not have permission to access.",
    "00021": "Access denied. You do not have permission to access.",
    "00022": "No id provided in params. Please enter an id.",
    "00023": "Provided id is not a valid object id.",
    "00024": "Too many request.",
    "00025": "Please provide all the required fields!",
    "00026": "Please provide a valid email!",
    "00027": "Please provide a password that is longer than 6 letters and shorter than 20 letters.",
    "00028": "Please provide a name that is longer than 3 letters and shorter than 30 letters.",
    "00029": "Please provide a valid email!",
    "00030": "Please provide a valid mobile no!",
    "00032": "An account with this email address already exists.",
    "00033": "An account with this mobile number already exists.",
    "00035": "You registered successfully.",
    "00036": "An account with this email address was not found.",
    "00038": "Please provide all the required fields!",
    "00039": "Please provide a valid credential!",
    "00040": "Please provide a password that is longer than 6 letters and shorter than 20 letters.",
    "00042": "An account with this email address was not found.",
    "00043": "Your email is not activated, please register firstly.",
    "00044": "Your email is not verified, please verify your email.",
    "00045": "You have entered an invalid email or password.",
    "00047": "You logged in successfully.",
    "00048": "The code is sent to your email successfully.",
    "00050": "Successfully logged out.",
    "00052": "The user could not find.",
    "00053": "Please send a verification code.",
    "00054": "The code you enter does not match with the code we sent to your email. Please check again.",
    "00055": "Invalid token. the token may have expired.",
    "00058": "Your email address was verified successfully.",
    "00059": "Please provide refresh token.",
    "00061": "The provided token does not match with the user, please login.",
    "00062": "The token has expired, please login.",
    "00063": "The token couldn\"t be verified, please login.",
    "00065": "The token is refreshed successfully.",
    "00066": "Please provide a password longer than 6, less than 20 characters.",
    "00068": "The new password was created successfully.",
    "00069": "Please provide old and new passwords that are longer than 6 letters and shorter than 20 letters.",
    "00072": "Your old password does not match with the password you entered, please enter the correct password.",
    "00073": "Your new password should not be same with the old one, please try a different password.",
    "00076": "Your password was changed successfully.",
    "00077": "Please provide a name that is longer than 3 letters and shorter than 30 letters.",
    "00078": "Valid gender options: female-male-other, plese provide one of them.",
    "00079": "Valid language options: mr-en, plese provide one of them.",
    "00080": "Please provide a valid birth date.",
    "00081": "Please provide a username that is longer than 3 letters and shorter than 15 letters.",
    "00084": "There is already a user with this username, please enter another.",
    "00085": "You have already updated your username.",
    "00086": "Your information was updated successfully.",
    "00087": "Your profile information was changed successfully.",
    "00089": "The user information has gotten successfully.",
    "00092": "Your account was deleted successfully.",
    "00093": "Incorrect Excel Sheet",
    "00094": "The result could not find.",
    "00099": "Already exists.",
    "00100": "Saved successfully.",
    "00101": "All information have gotten successfully.",
    "00102": "Information has gotten successfully.",
    "00103": "Deleted successfully.",
    "00104": "OTP sent successfully.",
    "00105": "OTP record not found.",
    "00106": "OTP has already been verified or expired.",
    "00107": "Incorrect OTP.",
    "00108": "OTP verified successfully.",
    "00109": "Please provide valid input.",
    "00120": "Unable to open this link. ",
    "00121": "Information has Updated successfully.",
    "00122": "Information not Updated successfully.",
    "00123": "Document Deletion Failed",
    "00124": "Data was deleted",
    "00125": "This number is already registered. Please sign in",
    "00126": "UnAuthorized Access !",

};